logo: Home
title: Dave Lively
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.resurgens.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: Mobile-Games.mp4 # add banner video. Add your video file to the folder video
banner-title: Dave Lively # add banner title
banner-desc: Self-taught web developer with a solid base of formal CS ed, now specializing in Elixir w/ Phoenix, Rails, React, and AngularJS. # add banner description

# Author settings
author-pic: face.png # your photo
author-name: Dave Lively
about-author: Dave is a self-taught web developer based in Atlanta, seeking to turn his passion into a career. Graduate of West Point, husband to Sarah, and avid Atlanta United supporter.
email: dlively@resurgens.io # your email
phone: (704) 759-6241 # your phone number
website: http://www.resurgens.io/ # you website

# Social link
linkedin_url: https://www.linkedin.com/in/livelydave/ # add url link
twitter_url: https://twitter.com/RealDaveLively  # add url link
github_url: https://github.com/davelively14

# Disqus
discus_identifier: resurgens-1 # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Add portfolio collection
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
